<script setup>
import { ref } from "vue";

const props = defineProps(["information"]);
const showToolTip = ref(false);

function changeView(show) {
  showToolTip.value = show;
}
// function view() {
//   let toolip = document.querySelector(".tooltip");
//   toolip.style.display = "flex";
// }
// function viewLeave() {
//   let toolip = document.querySelector(".tooltip");
//   toolip.style.display = "none";
// }
async function deleteInfo() {
  const id = props.information._id;
  const response = await axios.delete(`/productsModule?_id=${id}`);
  if (!response.error) information.value.push({ ...newProduct.value });
}
</script>
<template>
  <div class="card">
    <!-- <p>{{ props.information.name }}</p> -->
    <div class="card__product" @mouseleave="changeView(false)">
      <div class="tooltip swing-in-top-fwd" v-if="showToolTip">
        <button
          class="btn-tooltip"
          @click="changeView(), $router.push('/ecommers')"
        >
          Ver Producto
        </button>
      </div>
      <img
        class="card__product-img"
        :src="props.information.pictures[0]"
        @click="changeView(), $router.push('/ecommers')"
        @mouseover="changeView(true)"
      />
    </div>
    <div class="card__info">
      <span
        @click="changeView(), $router.push('/ecommers')"
        class="card__info-value"
        >{{ props.information.name }}</span
      >
    </div>
    <div class="card__price">
      <div class="card__container">
        <span class="card__price-value">${{ props.information.price }}</span>
      </div>
      <div class="btn__crud">
        <button @click="deleteInfo()" class="btn__delete">
          <i class="fa fa-times" aria-hidden="true"></i>
          Eliminar
        </button>
        <button @click="$emit('onEdit', props.information)" class="btn__edit">
          <i class="fa fa-pencil" aria-hidden="true"></i>
          Editar
        </button>
      </div>
    </div>
  </div>
</template>

<style>
.card {
  display: flex;
  flex-direction: column;
  align-content: center;
  background-color: #ffffff;
  width: 150px;
  height: 250px;
  border-radius: 10px;
  border: solid 5px #fff;
  padding: 10px;
  min-width: 126px;
  min-height: 215px;
}
.card__product {
  width: 100%;
  height: 70%;
}
.card__product-img {
  width: 100%;
  height: 100%;
  border-radius: 10px;
  cursor: pointer;
}
.card__info {
  display: flex;
  align-content: center;
  width: 100%;
  /* height: 50%; */
  margin-top: 5px;
  /* background-color: #fd0; */
  font-size: 20px;
}
.info__price-value {
  color: #000;
}
.card__price {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 93%;
  /* height: 40%; */
  color: #000;
  background-color: #c9bfbf;
  padding: 5px;
}
.card__container {
  /* display: flex;
  justify-content: end;
  align-content: center; */
  background-color: #beb9b9;
  font-size: 15px;
}

.card__info-value {
  padding: 3px;
  color: #000;
  cursor: pointer;
}
.tooltip {
  display: flex;
  position: absolute;
  transition: 0.5s;
}
.btn-tooltip {
  width: 100px;
  height: 30px;
  position: absolute;
  top: 10px;
  left: 5px;
  color: #fff;
  border: none;
  background-color: #11ca6d;
  cursor: pointer;
  transition: 0.5s;
}
.btn-tooltip:hover {
  background-color: #26b56d;
  border-radius: 7px;
  transition: 0.8s;
}
.swing-in-top-fwd {
  -webkit-animation: swing-in-top-fwd 0.5s
    cubic-bezier(0.175, 0.885, 0.32, 1.275) both;
  animation: swing-in-top-fwd 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) both;
}
.btn__delete {
  display: flex;
  justify-content: center;
  width: 100%;
  height: 100%;
  background-color: rgb(203, 54, 54);
  border: none;
  color: #fff;
  cursor: pointer;
  border-radius: 3px;
}
.btn__delete:hover {
  outline: solid 2px #000;
}
.btn__edit {
  display: flex;
  justify-content: center;
  gap: 5px;
  width: 100%;
  height: 100%;
  background-color: #166cec;
  color: #ffffff;
  border: none;
  cursor: pointer;
  border-radius: 3px;
}
.btn__edit:hover {
  outline: solid 2px #000;
  border-radius: 3px;
}
.btn__crud {
  display: flex;
  flex-direction: column;
  justify-content: end;
  gap: 5px;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-4-13 9:22:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-top-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
    transform: rotateX(-100deg);
    -webkit-transform-origin: top;
    transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
    transform: rotateX(0deg);
    -webkit-transform-origin: top;
    transform-origin: top;
    opacity: 1;
  }
}
@keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
    transform: rotateX(-100deg);
    -webkit-transform-origin: top;
    transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
    transform: rotateX(0deg);
    -webkit-transform-origin: top;
    transform-origin: top;
    opacity: 1;
  }
}
.card__price-value {
  color: #000;
  font-family: monospace;
  font-size: 18px;
}
@media (max-width: 300px) {
  .card {
    width: 126px;
    height: 215px;
  }
}
</style>
